# Generated by Django 4.2.4 on 2023-08-26 11:06

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("roll_number", models.CharField(max_length=10)),
                ("phone_number", models.CharField(max_length=15)),
                ("rollnumber_name", models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
